/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as AuthenticatedTrustRouteImport } from './routes/_authenticated/trust'
import { Route as AuthenticatedTalentsRouteImport } from './routes/_authenticated/talents'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFlashRouteImport } from './routes/_authenticated/flash'
import { Route as AuthenticatedCreationRouteImport } from './routes/_authenticated/creation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrustRoute = AuthenticatedTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalentsRoute = AuthenticatedTalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashRoute = AuthenticatedFlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreationRoute = AuthenticatedCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/flash': typeof AuthenticatedFlashRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/scan': typeof AuthenticatedScanRoute
  '/talents': typeof AuthenticatedTalentsRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/flash': typeof AuthenticatedFlashRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/scan': typeof AuthenticatedScanRoute
  '/talents': typeof AuthenticatedTalentsRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/creation': typeof AuthenticatedCreationRoute
  '/_authenticated/flash': typeof AuthenticatedFlashRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/talents': typeof AuthenticatedTalentsRoute
  '/_authenticated/trust': typeof AuthenticatedTrustRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/notifications'
    | '/admin'
    | '/creation'
    | '/flash'
    | '/profile'
    | '/radar'
    | '/scan'
    | '/talents'
    | '/trust'
    | '/api/assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/notifications'
    | '/admin'
    | '/creation'
    | '/flash'
    | '/profile'
    | '/radar'
    | '/scan'
    | '/talents'
    | '/trust'
    | '/api/assistant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/messages'
    | '/notifications'
    | '/_authenticated/admin'
    | '/_authenticated/creation'
    | '/_authenticated/flash'
    | '/_authenticated/profile'
    | '/_authenticated/radar'
    | '/_authenticated/scan'
    | '/_authenticated/talents'
    | '/_authenticated/trust'
    | '/api/assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trust': {
      id: '/_authenticated/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AuthenticatedTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talents': {
      id: '/_authenticated/talents'
      path: '/talents'
      fullPath: '/talents'
      preLoaderRoute: typeof AuthenticatedTalentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flash': {
      id: '/_authenticated/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof AuthenticatedFlashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creation': {
      id: '/_authenticated/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof AuthenticatedCreationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreationRoute: typeof AuthenticatedCreationRoute
  AuthenticatedFlashRoute: typeof AuthenticatedFlashRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedTalentsRoute: typeof AuthenticatedTalentsRoute
  AuthenticatedTrustRoute: typeof AuthenticatedTrustRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreationRoute: AuthenticatedCreationRoute,
  AuthenticatedFlashRoute: AuthenticatedFlashRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedTalentsRoute: AuthenticatedTalentsRoute,
  AuthenticatedTrustRoute: AuthenticatedTrustRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ApiAssistantRoute: ApiAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
